### PR TITLE
Wrap headers with AxiosHeaders to prevent incorrect type being passed

### LINKED ISSUE #1250: TypeError: t.getContentType is not a function at Oe.transformRequest
We have experienced issues with the latest version of axios (1.6.3) passing through bad header objects which are not of the correct type which causes the below error from the transformRequest method in axios.

```
ERROR TypeError: t.getContentType is not a function at Oe.transformRequest
```

### PR DESCRIPTION
**Pull request by danielcooperxyz**
We have experienced issues with the latest version of axios (`1.6.3`) passing through bad header objects which are not of the correct type which causes the below error from the `transformRequest` method in axios.

```
ERROR TypeError: t.getContentType is not a function at Oe.transformRequest
```

This PR includes a new line that will wrap the header object each time regardless of what is passed, to enforce that the correct type is then passed to the transformRequest transformer function.

Fixes #1250

### CODE REVIEW

**Comment by loukmane-issa** [comment]
> and in the mean time, how are you including this in your `package.json`?

Did you get any chance at all with this? I'm experiencing the same issue and it would be a shame to have to write my own :(

File: src/interceptor.ts [hunk 1]
```diff
@@ -130,7 +130,8 @@ export const aws4Interceptor = <D = any>({
     }
 
     const { host, pathname, search } = new URL(url);
-    const { data, headers, method } = config;
+    const { data, method } = config;
+    const headers = new AxiosHeaders(config.headers);
```
Comment (BourgoisMickael) [inline src/interceptor.ts:134]: Maybe you should fix the actual headers when they are set at line 170:

https://github.com/jamesmbourne/aws4-axios/pull/1248/files#diff-bc2f1f907be8c49520a585dda7f0c100645e31e9bedf3828c3850fdf8389e619R170

```ts
config.headers = signingOptions.headers as AxiosHeaders;
```

This should not be casted but should be a real AxiosHeaders instance. Otherwise this lib will still break axios for every other uses outside this lib.

**Comment by BourgoisMickael** [comment]
If a maintainer could look into this quickly, it would be nice. It's just a oneliner.

Here is a workaround in the meantime:

```js
axios.interceptors.request.use(async req => {
    const signedReq = await interceptor(req);
    signedReq.headers = new axios.AxiosHeaders(signedReq.headers);
    return signedReq;
});
```

**Comment by jamesmbourne** [comment]
Hey @danielcooperxyz, thanks for putting this fix in. I'll try and get this merged & released today 🤞
